#ifndef _MODULE_SMISC_KJO_Ufdi44_REGS_H_
#define _MODULE_SMISC_KJO_Ufdi44_REGS_H_
#ifdef __cplusplus
 extern "C" {
#endif
/* ----------------------------------------------------------------------------
   -- SMISC Peripheral Access Layer
   ---------------------------------------------------------------------------- */
/**
 * @addtogroup SMISC_Peripheral_Access_Layer SMISC Peripheral Access Layer
 * @{
 */
/** SMISC - Size of Registers Arrays */
/** SMISC - Register Layout Typedef */
typedef struct {
       uint8_t  RESERVED_0[4];
  __IO uint32_t CHIPCTLR                      ; /* Chip Control Register, offset: 0x4 */
       uint8_t  RESERVED_1[4];
  __IO uint32_t FTUOPTR0                      ; /* FTU Option Register 0, offset: 0xC */
  __IO uint32_t AONCLKSR                      ; /* AON Clock Select Register, offset: 0x10 */
       uint8_t  RESERVED_2[4];
  __IO uint32_t ADCOPTR                       ; /* ADC Options Register, offset: 0x18 */
  __IO uint32_t FTUOPTR1                      ; /* FTU Option Register 1, offset: 0x1C */
  __IO uint32_t PERICTLR                      ; /* Peripheral Control Register, offset: 0x20 */
  __I  uint32_t SDID                          ; /* System Device Identification Register, offset: 0x24 */
       uint8_t  RESERVED_3[24];
  __IO uint32_t SYSCGC                        ; /* System Clock Gating Control Register, offset: 0x40 */
       uint8_t  RESERVED_4[16];
  __I  uint32_t UID3                          ; /* Unique Identification Register 3, offset: 0x54 */
  __I  uint32_t UID2                          ; /* Unique Identification Register 2, offset: 0x58 */
  __I  uint32_t UID1                          ; /* Unique Identification Register 1, offset: 0x5C */
  __I  uint32_t UID0                          ; /* Unique Identification Register 0, offset: 0x60 */
       uint8_t  RESERVED_5[4];
  __IO uint32_t TRACECLKDIV                   ; /* Trace Clock Divider Register, offset: 0x68 */
  __IO uint32_t SOFTCTRL                      ; /* Software Control Register, offset: 0x6C */
       uint8_t  RESERVED_6[4];
  __IO uint32_t STATCTRL                      ; /* Status Control Register, offset: 0x74 */
  __IO uint32_t RNGCNTR                       ; /* RNG Counter Register, offset: 0x78 */
       uint8_t  RESERVED_7[4];
  __IO uint32_t PERIMUX0                      ; /* Peripheral Mux Control Register 0, offset: 0x80 */
  __IO uint32_t PERIMUX1                      ; /* Peripheral Mux Control Register 1, offset: 0x84 */
       uint8_t  RESERVED_8[24];
  __IO uint32_t STOPMODE0                     ; /* STOP Mode Control0 Register, offset: 0xA0 */
  __IO uint32_t STOPMODE1                     ; /* STOP Mode Control1 Register, offset: 0xA4 */
  __IO uint32_t STOPMODE2                     ; /* STOP Mode Control2 Register, offset: 0xA8 */
} SMISC_Type, *SMISC_MemMapPtr;

/* ----------------------------------------------------------------------------
   -- SMISC Register Masks
   ---------------------------------------------------------------------------- */
/**
 * @addtogroup SMISC_Register_Masks SMISC Register Masks
 * @{
 */
 
/* CHIPCTLR Bit Fields */
#define SMISC_CHIPCTLR_PTIMER_BTB_SEL_MASK 0x2000u
#define SMISC_CHIPCTLR_PTIMER_BTB_SEL_SHIFT 13u
#define SMISC_CHIPCTLR_PTIMER_BTB_SEL_WIDTH 1u
#define SMISC_CHIPCTLR_PTIMER_BTB_SEL(x) (((uint32_t)(((uint32_t)(x))<<SMISC_CHIPCTLR_PTIMER_BTB_SEL_SHIFT))&SMISC_CHIPCTLR_PTIMER_BTB_SEL_MASK)
#define SMISC_CHIPCTLR_CLKOUTEN_MASK   0x800u
#define SMISC_CHIPCTLR_CLKOUTEN_SHIFT  11u
#define SMISC_CHIPCTLR_CLKOUTEN_WIDTH  1u
#define SMISC_CHIPCTLR_CLKOUTEN(x)     (((uint32_t)(((uint32_t)(x))<<SMISC_CHIPCTLR_CLKOUTEN_SHIFT))&SMISC_CHIPCTLR_CLKOUTEN_MASK)
#define SMISC_CHIPCTLR_CLKOUTDIV_MASK  0x700u
#define SMISC_CHIPCTLR_CLKOUTDIV_SHIFT 8u
#define SMISC_CHIPCTLR_CLKOUTDIV_WIDTH 3u
#define SMISC_CHIPCTLR_CLKOUTDIV(x)    (((uint32_t)(((uint32_t)(x))<<SMISC_CHIPCTLR_CLKOUTDIV_SHIFT))&SMISC_CHIPCTLR_CLKOUTDIV_MASK)
#define SMISC_CHIPCTLR_CLKOUTSEL_MASK  0xF0u
#define SMISC_CHIPCTLR_CLKOUTSEL_SHIFT 4u
#define SMISC_CHIPCTLR_CLKOUTSEL_WIDTH 4u
#define SMISC_CHIPCTLR_CLKOUTSEL(x)    (((uint32_t)(((uint32_t)(x))<<SMISC_CHIPCTLR_CLKOUTSEL_SHIFT))&SMISC_CHIPCTLR_CLKOUTSEL_MASK)
/* CHIPCTLR Reg Mask */
#define SMISC_CHIPCTLR_MASK            0x00002FF0u
/* FTUOPTR0 Bit Fields */
#define SMISC_FTUOPTR0_FTU3CLKSEL_MASK 0xC0000000u
#define SMISC_FTUOPTR0_FTU3CLKSEL_SHIFT 30u
#define SMISC_FTUOPTR0_FTU3CLKSEL_WIDTH 2u
#define SMISC_FTUOPTR0_FTU3CLKSEL(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR0_FTU3CLKSEL_SHIFT))&SMISC_FTUOPTR0_FTU3CLKSEL_MASK)
#define SMISC_FTUOPTR0_FTU2CLKSEL_MASK 0x30000000u
#define SMISC_FTUOPTR0_FTU2CLKSEL_SHIFT 28u
#define SMISC_FTUOPTR0_FTU2CLKSEL_WIDTH 2u
#define SMISC_FTUOPTR0_FTU2CLKSEL(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR0_FTU2CLKSEL_SHIFT))&SMISC_FTUOPTR0_FTU2CLKSEL_MASK)
#define SMISC_FTUOPTR0_FTU1CLKSEL_MASK 0xC000000u
#define SMISC_FTUOPTR0_FTU1CLKSEL_SHIFT 26u
#define SMISC_FTUOPTR0_FTU1CLKSEL_WIDTH 2u
#define SMISC_FTUOPTR0_FTU1CLKSEL(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR0_FTU1CLKSEL_SHIFT))&SMISC_FTUOPTR0_FTU1CLKSEL_MASK)
#define SMISC_FTUOPTR0_FTU0CLKSEL_MASK 0x3000000u
#define SMISC_FTUOPTR0_FTU0CLKSEL_SHIFT 24u
#define SMISC_FTUOPTR0_FTU0CLKSEL_WIDTH 2u
#define SMISC_FTUOPTR0_FTU0CLKSEL(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR0_FTU0CLKSEL_SHIFT))&SMISC_FTUOPTR0_FTU0CLKSEL_MASK)
#define SMISC_FTUOPTR0_FTU7CLKSEL_MASK 0xC00000u
#define SMISC_FTUOPTR0_FTU7CLKSEL_SHIFT 22u
#define SMISC_FTUOPTR0_FTU7CLKSEL_WIDTH 2u
#define SMISC_FTUOPTR0_FTU7CLKSEL(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR0_FTU7CLKSEL_SHIFT))&SMISC_FTUOPTR0_FTU7CLKSEL_MASK)
#define SMISC_FTUOPTR0_FTU6CLKSEL_MASK 0x300000u
#define SMISC_FTUOPTR0_FTU6CLKSEL_SHIFT 20u
#define SMISC_FTUOPTR0_FTU6CLKSEL_WIDTH 2u
#define SMISC_FTUOPTR0_FTU6CLKSEL(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR0_FTU6CLKSEL_SHIFT))&SMISC_FTUOPTR0_FTU6CLKSEL_MASK)
#define SMISC_FTUOPTR0_FTU5CLKSEL_MASK 0xC0000u
#define SMISC_FTUOPTR0_FTU5CLKSEL_SHIFT 18u
#define SMISC_FTUOPTR0_FTU5CLKSEL_WIDTH 2u
#define SMISC_FTUOPTR0_FTU5CLKSEL(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR0_FTU5CLKSEL_SHIFT))&SMISC_FTUOPTR0_FTU5CLKSEL_MASK)
#define SMISC_FTUOPTR0_FTU4CLKSEL_MASK 0x30000u
#define SMISC_FTUOPTR0_FTU4CLKSEL_SHIFT 16u
#define SMISC_FTUOPTR0_FTU4CLKSEL_WIDTH 2u
#define SMISC_FTUOPTR0_FTU4CLKSEL(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR0_FTU4CLKSEL_SHIFT))&SMISC_FTUOPTR0_FTU4CLKSEL_MASK)
/* FTUOPTR0 Reg Mask */
#define SMISC_FTUOPTR0_MASK            0xFFFF0000u
/* AONCLKSR Bit Fields */
#define SMISC_AONCLKSR_AON32KCLKSEL_MASK 0xC0u
#define SMISC_AONCLKSR_AON32KCLKSEL_SHIFT 6u
#define SMISC_AONCLKSR_AON32KCLKSEL_WIDTH 2u
#define SMISC_AONCLKSR_AON32KCLKSEL(x) (((uint32_t)(((uint32_t)(x))<<SMISC_AONCLKSR_AON32KCLKSEL_SHIFT))&SMISC_AONCLKSR_AON32KCLKSEL_MASK)
#define SMISC_AONCLKSR_RTCCLKSEL_MASK  0x30u
#define SMISC_AONCLKSR_RTCCLKSEL_SHIFT 4u
#define SMISC_AONCLKSR_RTCCLKSEL_WIDTH 2u
#define SMISC_AONCLKSR_RTCCLKSEL(x)    (((uint32_t)(((uint32_t)(x))<<SMISC_AONCLKSR_RTCCLKSEL_SHIFT))&SMISC_AONCLKSR_RTCCLKSEL_MASK)
#define SMISC_AONCLKSR_AONCLKSEL_MASK  0xCu
#define SMISC_AONCLKSR_AONCLKSEL_SHIFT 2u
#define SMISC_AONCLKSR_AONCLKSEL_WIDTH 2u
#define SMISC_AONCLKSR_AONCLKSEL(x)    (((uint32_t)(((uint32_t)(x))<<SMISC_AONCLKSR_AONCLKSEL_SHIFT))&SMISC_AONCLKSR_AONCLKSEL_MASK)
#define SMISC_AONCLKSR_SIRCDIV32KEN_MASK 0x2u
#define SMISC_AONCLKSR_SIRCDIV32KEN_SHIFT 1u
#define SMISC_AONCLKSR_SIRCDIV32KEN_WIDTH 1u
#define SMISC_AONCLKSR_SIRCDIV32KEN(x) (((uint32_t)(((uint32_t)(x))<<SMISC_AONCLKSR_SIRCDIV32KEN_SHIFT))&SMISC_AONCLKSR_SIRCDIV32KEN_MASK)
#define SMISC_AONCLKSR_AON1KCLKEN_MASK 0x1u
#define SMISC_AONCLKSR_AON1KCLKEN_SHIFT 0u
#define SMISC_AONCLKSR_AON1KCLKEN_WIDTH 1u
#define SMISC_AONCLKSR_AON1KCLKEN(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_AONCLKSR_AON1KCLKEN_SHIFT))&SMISC_AONCLKSR_AON1KCLKEN_MASK)
/* AONCLKSR Reg Mask */
#define SMISC_AONCLKSR_MASK            0x000000FFu
/* ADCOPTR Bit Fields */
#define SMISC_ADCOPTR_ADC1PRETRGSEL_MASK 0x3000u
#define SMISC_ADCOPTR_ADC1PRETRGSEL_SHIFT 12u
#define SMISC_ADCOPTR_ADC1PRETRGSEL_WIDTH 2u
#define SMISC_ADCOPTR_ADC1PRETRGSEL(x) (((uint32_t)(((uint32_t)(x))<<SMISC_ADCOPTR_ADC1PRETRGSEL_SHIFT))&SMISC_ADCOPTR_ADC1PRETRGSEL_MASK)
#define SMISC_ADCOPTR_ADC1SWPRETRG_MASK 0xE00u
#define SMISC_ADCOPTR_ADC1SWPRETRG_SHIFT 9u
#define SMISC_ADCOPTR_ADC1SWPRETRG_WIDTH 3u
#define SMISC_ADCOPTR_ADC1SWPRETRG(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_ADCOPTR_ADC1SWPRETRG_SHIFT))&SMISC_ADCOPTR_ADC1SWPRETRG_MASK)
#define SMISC_ADCOPTR_ADC1TRGSEL_MASK  0x100u
#define SMISC_ADCOPTR_ADC1TRGSEL_SHIFT 8u
#define SMISC_ADCOPTR_ADC1TRGSEL_WIDTH 1u
#define SMISC_ADCOPTR_ADC1TRGSEL(x)    (((uint32_t)(((uint32_t)(x))<<SMISC_ADCOPTR_ADC1TRGSEL_SHIFT))&SMISC_ADCOPTR_ADC1TRGSEL_MASK)
#define SMISC_ADCOPTR_ADC0PRETRGSEL_MASK 0x30u
#define SMISC_ADCOPTR_ADC0PRETRGSEL_SHIFT 4u
#define SMISC_ADCOPTR_ADC0PRETRGSEL_WIDTH 2u
#define SMISC_ADCOPTR_ADC0PRETRGSEL(x) (((uint32_t)(((uint32_t)(x))<<SMISC_ADCOPTR_ADC0PRETRGSEL_SHIFT))&SMISC_ADCOPTR_ADC0PRETRGSEL_MASK)
#define SMISC_ADCOPTR_ADC0SWPRETRG_MASK 0xEu
#define SMISC_ADCOPTR_ADC0SWPRETRG_SHIFT 1u
#define SMISC_ADCOPTR_ADC0SWPRETRG_WIDTH 3u
#define SMISC_ADCOPTR_ADC0SWPRETRG(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_ADCOPTR_ADC0SWPRETRG_SHIFT))&SMISC_ADCOPTR_ADC0SWPRETRG_MASK)
#define SMISC_ADCOPTR_ADC0TRGSEL_MASK  0x1u
#define SMISC_ADCOPTR_ADC0TRGSEL_SHIFT 0u
#define SMISC_ADCOPTR_ADC0TRGSEL_WIDTH 1u
#define SMISC_ADCOPTR_ADC0TRGSEL(x)    (((uint32_t)(((uint32_t)(x))<<SMISC_ADCOPTR_ADC0TRGSEL_SHIFT))&SMISC_ADCOPTR_ADC0TRGSEL_MASK)
/* ADCOPTR Reg Mask */
#define SMISC_ADCOPTR_MASK             0x00003F3Fu
/* FTUOPTR1 Bit Fields */
#define SMISC_FTUOPTR1_FTU3_OUTSEL_MASK 0xFF000000u
#define SMISC_FTUOPTR1_FTU3_OUTSEL_SHIFT 24u
#define SMISC_FTUOPTR1_FTU3_OUTSEL_WIDTH 8u
#define SMISC_FTUOPTR1_FTU3_OUTSEL(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR1_FTU3_OUTSEL_SHIFT))&SMISC_FTUOPTR1_FTU3_OUTSEL_MASK)
#define SMISC_FTUOPTR1_FTU0_OUTSEL_MASK 0xFF0000u
#define SMISC_FTUOPTR1_FTU0_OUTSEL_SHIFT 16u
#define SMISC_FTUOPTR1_FTU0_OUTSEL_WIDTH 8u
#define SMISC_FTUOPTR1_FTU0_OUTSEL(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR1_FTU0_OUTSEL_SHIFT))&SMISC_FTUOPTR1_FTU0_OUTSEL_MASK)
#define SMISC_FTUOPTR1_FTU7SYNC_MASK   0x4000u
#define SMISC_FTUOPTR1_FTU7SYNC_SHIFT  14u
#define SMISC_FTUOPTR1_FTU7SYNC_WIDTH  1u
#define SMISC_FTUOPTR1_FTU7SYNC(x)     (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR1_FTU7SYNC_SHIFT))&SMISC_FTUOPTR1_FTU7SYNC_MASK)
#define SMISC_FTUOPTR1_FTU6SYNC_MASK   0x2000u
#define SMISC_FTUOPTR1_FTU6SYNC_SHIFT  13u
#define SMISC_FTUOPTR1_FTU6SYNC_WIDTH  1u
#define SMISC_FTUOPTR1_FTU6SYNC(x)     (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR1_FTU6SYNC_SHIFT))&SMISC_FTUOPTR1_FTU6SYNC_MASK)
#define SMISC_FTUOPTR1_FTU5SYNC_MASK   0x1000u
#define SMISC_FTUOPTR1_FTU5SYNC_SHIFT  12u
#define SMISC_FTUOPTR1_FTU5SYNC_WIDTH  1u
#define SMISC_FTUOPTR1_FTU5SYNC(x)     (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR1_FTU5SYNC_SHIFT))&SMISC_FTUOPTR1_FTU5SYNC_MASK)
#define SMISC_FTUOPTR1_FTU4SYNC_MASK   0x800u
#define SMISC_FTUOPTR1_FTU4SYNC_SHIFT  11u
#define SMISC_FTUOPTR1_FTU4SYNC_WIDTH  1u
#define SMISC_FTUOPTR1_FTU4SYNC(x)     (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR1_FTU4SYNC_SHIFT))&SMISC_FTUOPTR1_FTU4SYNC_MASK)
#define SMISC_FTUOPTR1_FTU2CH1SEL_MASK 0x100u
#define SMISC_FTUOPTR1_FTU2CH1SEL_SHIFT 8u
#define SMISC_FTUOPTR1_FTU2CH1SEL_WIDTH 1u
#define SMISC_FTUOPTR1_FTU2CH1SEL(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR1_FTU2CH1SEL_SHIFT))&SMISC_FTUOPTR1_FTU2CH1SEL_MASK)
#define SMISC_FTUOPTR1_FTU2CH0SEL_MASK 0xC0u
#define SMISC_FTUOPTR1_FTU2CH0SEL_SHIFT 6u
#define SMISC_FTUOPTR1_FTU2CH0SEL_WIDTH 2u
#define SMISC_FTUOPTR1_FTU2CH0SEL(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR1_FTU2CH0SEL_SHIFT))&SMISC_FTUOPTR1_FTU2CH0SEL_MASK)
#define SMISC_FTUOPTR1_FTU1CH0SEL_MASK 0x30u
#define SMISC_FTUOPTR1_FTU1CH0SEL_SHIFT 4u
#define SMISC_FTUOPTR1_FTU1CH0SEL_WIDTH 2u
#define SMISC_FTUOPTR1_FTU1CH0SEL(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR1_FTU1CH0SEL_SHIFT))&SMISC_FTUOPTR1_FTU1CH0SEL_MASK)
#define SMISC_FTUOPTR1_FTU3SYNC_MASK   0x8u
#define SMISC_FTUOPTR1_FTU3SYNC_SHIFT  3u
#define SMISC_FTUOPTR1_FTU3SYNC_WIDTH  1u
#define SMISC_FTUOPTR1_FTU3SYNC(x)     (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR1_FTU3SYNC_SHIFT))&SMISC_FTUOPTR1_FTU3SYNC_MASK)
#define SMISC_FTUOPTR1_FTU2SYNC_MASK   0x4u
#define SMISC_FTUOPTR1_FTU2SYNC_SHIFT  2u
#define SMISC_FTUOPTR1_FTU2SYNC_WIDTH  1u
#define SMISC_FTUOPTR1_FTU2SYNC(x)     (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR1_FTU2SYNC_SHIFT))&SMISC_FTUOPTR1_FTU2SYNC_MASK)
#define SMISC_FTUOPTR1_FTU1SYNC_MASK   0x2u
#define SMISC_FTUOPTR1_FTU1SYNC_SHIFT  1u
#define SMISC_FTUOPTR1_FTU1SYNC_WIDTH  1u
#define SMISC_FTUOPTR1_FTU1SYNC(x)     (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR1_FTU1SYNC_SHIFT))&SMISC_FTUOPTR1_FTU1SYNC_MASK)
#define SMISC_FTUOPTR1_FTU0SYNC_MASK   0x1u
#define SMISC_FTUOPTR1_FTU0SYNC_SHIFT  0u
#define SMISC_FTUOPTR1_FTU0SYNC_WIDTH  1u
#define SMISC_FTUOPTR1_FTU0SYNC(x)     (((uint32_t)(((uint32_t)(x))<<SMISC_FTUOPTR1_FTU0SYNC_SHIFT))&SMISC_FTUOPTR1_FTU0SYNC_MASK)
/* FTUOPTR1 Reg Mask */
#define SMISC_FTUOPTR1_MASK            0xFFFF79FFu
/* PERICTLR Bit Fields */
#define SMISC_PERICTLR_ENET_CLK_SW_RESET_MASK 0x8000000u
#define SMISC_PERICTLR_ENET_CLK_SW_RESET_SHIFT 27u
#define SMISC_PERICTLR_ENET_CLK_SW_RESET_WIDTH 1u
#define SMISC_PERICTLR_ENET_CLK_SW_RESET(x) (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_ENET_CLK_SW_RESET_SHIFT))&SMISC_PERICTLR_ENET_CLK_SW_RESET_MASK)
#define SMISC_PERICTLR_RMII_CLK_SEL_MASK 0x2000000u
#define SMISC_PERICTLR_RMII_CLK_SEL_SHIFT 25u
#define SMISC_PERICTLR_RMII_CLK_SEL_WIDTH 1u
#define SMISC_PERICTLR_RMII_CLK_SEL(x) (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_RMII_CLK_SEL_SHIFT))&SMISC_PERICTLR_RMII_CLK_SEL_MASK)
#define SMISC_PERICTLR_RMII_CLK_OBE_MASK 0x1000000u
#define SMISC_PERICTLR_RMII_CLK_OBE_SHIFT 24u
#define SMISC_PERICTLR_RMII_CLK_OBE_WIDTH 1u
#define SMISC_PERICTLR_RMII_CLK_OBE(x) (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_RMII_CLK_OBE_SHIFT))&SMISC_PERICTLR_RMII_CLK_OBE_MASK)
#define SMISC_PERICTLR_FTU7_OBECTL_MASK 0x800000u
#define SMISC_PERICTLR_FTU7_OBECTL_SHIFT 23u
#define SMISC_PERICTLR_FTU7_OBECTL_WIDTH 1u
#define SMISC_PERICTLR_FTU7_OBECTL(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_FTU7_OBECTL_SHIFT))&SMISC_PERICTLR_FTU7_OBECTL_MASK)
#define SMISC_PERICTLR_FTU6_OBECTL_MASK 0x400000u
#define SMISC_PERICTLR_FTU6_OBECTL_SHIFT 22u
#define SMISC_PERICTLR_FTU6_OBECTL_WIDTH 1u
#define SMISC_PERICTLR_FTU6_OBECTL(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_FTU6_OBECTL_SHIFT))&SMISC_PERICTLR_FTU6_OBECTL_MASK)
#define SMISC_PERICTLR_FTU5_OBECTL_MASK 0x200000u
#define SMISC_PERICTLR_FTU5_OBECTL_SHIFT 21u
#define SMISC_PERICTLR_FTU5_OBECTL_WIDTH 1u
#define SMISC_PERICTLR_FTU5_OBECTL(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_FTU5_OBECTL_SHIFT))&SMISC_PERICTLR_FTU5_OBECTL_MASK)
#define SMISC_PERICTLR_FTU4_OBECTL_MASK 0x100000u
#define SMISC_PERICTLR_FTU4_OBECTL_SHIFT 20u
#define SMISC_PERICTLR_FTU4_OBECTL_WIDTH 1u
#define SMISC_PERICTLR_FTU4_OBECTL(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_FTU4_OBECTL_SHIFT))&SMISC_PERICTLR_FTU4_OBECTL_MASK)
#define SMISC_PERICTLR_FTU3_OBECTL_MASK 0x80000u
#define SMISC_PERICTLR_FTU3_OBECTL_SHIFT 19u
#define SMISC_PERICTLR_FTU3_OBECTL_WIDTH 1u
#define SMISC_PERICTLR_FTU3_OBECTL(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_FTU3_OBECTL_SHIFT))&SMISC_PERICTLR_FTU3_OBECTL_MASK)
#define SMISC_PERICTLR_FTU2_OBECTL_MASK 0x40000u
#define SMISC_PERICTLR_FTU2_OBECTL_SHIFT 18u
#define SMISC_PERICTLR_FTU2_OBECTL_WIDTH 1u
#define SMISC_PERICTLR_FTU2_OBECTL(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_FTU2_OBECTL_SHIFT))&SMISC_PERICTLR_FTU2_OBECTL_MASK)
#define SMISC_PERICTLR_FTU1_OBECTL_MASK 0x20000u
#define SMISC_PERICTLR_FTU1_OBECTL_SHIFT 17u
#define SMISC_PERICTLR_FTU1_OBECTL_WIDTH 1u
#define SMISC_PERICTLR_FTU1_OBECTL(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_FTU1_OBECTL_SHIFT))&SMISC_PERICTLR_FTU1_OBECTL_MASK)
#define SMISC_PERICTLR_FTU0_OBECTL_MASK 0x10000u
#define SMISC_PERICTLR_FTU0_OBECTL_SHIFT 16u
#define SMISC_PERICTLR_FTU0_OBECTL_WIDTH 1u
#define SMISC_PERICTLR_FTU0_OBECTL(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_FTU0_OBECTL_SHIFT))&SMISC_PERICTLR_FTU0_OBECTL_MASK)
#define SMISC_PERICTLR_FTU_GTBCTRL_MASK 0x4000u
#define SMISC_PERICTLR_FTU_GTBCTRL_SHIFT 14u
#define SMISC_PERICTLR_FTU_GTBCTRL_WIDTH 1u
#define SMISC_PERICTLR_FTU_GTBCTRL(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_FTU_GTBCTRL_SHIFT))&SMISC_PERICTLR_FTU_GTBCTRL_MASK)
#define SMISC_PERICTLR_ENET_PPS3_OBECTL_MASK 0x800u
#define SMISC_PERICTLR_ENET_PPS3_OBECTL_SHIFT 11u
#define SMISC_PERICTLR_ENET_PPS3_OBECTL_WIDTH 1u
#define SMISC_PERICTLR_ENET_PPS3_OBECTL(x) (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_ENET_PPS3_OBECTL_SHIFT))&SMISC_PERICTLR_ENET_PPS3_OBECTL_MASK)
#define SMISC_PERICTLR_ENET_PPS2_OBECTL_MASK 0x400u
#define SMISC_PERICTLR_ENET_PPS2_OBECTL_SHIFT 10u
#define SMISC_PERICTLR_ENET_PPS2_OBECTL_WIDTH 1u
#define SMISC_PERICTLR_ENET_PPS2_OBECTL(x) (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_ENET_PPS2_OBECTL_SHIFT))&SMISC_PERICTLR_ENET_PPS2_OBECTL_MASK)
#define SMISC_PERICTLR_ENET_PPS1_OBECTL_MASK 0x200u
#define SMISC_PERICTLR_ENET_PPS1_OBECTL_SHIFT 9u
#define SMISC_PERICTLR_ENET_PPS1_OBECTL_WIDTH 1u
#define SMISC_PERICTLR_ENET_PPS1_OBECTL(x) (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_ENET_PPS1_OBECTL_SHIFT))&SMISC_PERICTLR_ENET_PPS1_OBECTL_MASK)
#define SMISC_PERICTLR_ENET_PPS0_OBECTL_MASK 0x100u
#define SMISC_PERICTLR_ENET_PPS0_OBECTL_SHIFT 8u
#define SMISC_PERICTLR_ENET_PPS0_OBECTL_WIDTH 1u
#define SMISC_PERICTLR_ENET_PPS0_OBECTL(x) (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_ENET_PPS0_OBECTL_SHIFT))&SMISC_PERICTLR_ENET_PPS0_OBECTL_MASK)
#define SMISC_PERICTLR_ENET_RMIIEN_MASK 0x80u
#define SMISC_PERICTLR_ENET_RMIIEN_SHIFT 7u
#define SMISC_PERICTLR_ENET_RMIIEN_WIDTH 1u
#define SMISC_PERICTLR_ENET_RMIIEN(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_ENET_RMIIEN_SHIFT))&SMISC_PERICTLR_ENET_RMIIEN_MASK)
#define SMISC_PERICTLR_ENET_TS_CLKSEL_MASK 0x8u
#define SMISC_PERICTLR_ENET_TS_CLKSEL_SHIFT 3u
#define SMISC_PERICTLR_ENET_TS_CLKSEL_WIDTH 1u
#define SMISC_PERICTLR_ENET_TS_CLKSEL(x) (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_ENET_TS_CLKSEL_SHIFT))&SMISC_PERICTLR_ENET_TS_CLKSEL_MASK)
#define SMISC_PERICTLR_ENET_5M_MODE_MASK 0x4u
#define SMISC_PERICTLR_ENET_5M_MODE_SHIFT 2u
#define SMISC_PERICTLR_ENET_5M_MODE_WIDTH 1u
#define SMISC_PERICTLR_ENET_5M_MODE(x) (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_ENET_5M_MODE_SHIFT))&SMISC_PERICTLR_ENET_5M_MODE_MASK)
#define SMISC_PERICTLR_I2S1_MCLKEN_MASK 0x2u
#define SMISC_PERICTLR_I2S1_MCLKEN_SHIFT 1u
#define SMISC_PERICTLR_I2S1_MCLKEN_WIDTH 1u
#define SMISC_PERICTLR_I2S1_MCLKEN(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_I2S1_MCLKEN_SHIFT))&SMISC_PERICTLR_I2S1_MCLKEN_MASK)
#define SMISC_PERICTLR_I2S0_MCLKEN_MASK 0x1u
#define SMISC_PERICTLR_I2S0_MCLKEN_SHIFT 0u
#define SMISC_PERICTLR_I2S0_MCLKEN_WIDTH 1u
#define SMISC_PERICTLR_I2S0_MCLKEN(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERICTLR_I2S0_MCLKEN_SHIFT))&SMISC_PERICTLR_I2S0_MCLKEN_MASK)
/* PERICTLR Reg Mask */
#define SMISC_PERICTLR_MASK            0x0BFF4F8Fu
/* SDID Bit Fields */
#define SMISC_SDID_DEVICE_ID_MASK      0xFFFFFFFFu
#define SMISC_SDID_DEVICE_ID_SHIFT     0u
#define SMISC_SDID_DEVICE_ID_WIDTH     32u
#define SMISC_SDID_DEVICE_ID(x)        (((uint32_t)(((uint32_t)(x))<<SMISC_SDID_DEVICE_ID_SHIFT))&SMISC_SDID_DEVICE_ID_MASK)
/* SDID Reg Mask */
#define SMISC_SDID_MASK                0xFFFFFFFFu
/* SYSCGC Bit Fields */
#define SMISC_SYSCGC_CGCISM_MASK       0x80u
#define SMISC_SYSCGC_CGCISM_SHIFT      7u
#define SMISC_SYSCGC_CGCISM_WIDTH      1u
#define SMISC_SYSCGC_CGCISM(x)         (((uint32_t)(((uint32_t)(x))<<SMISC_SYSCGC_CGCISM_SHIFT))&SMISC_SYSCGC_CGCISM_MASK)
#define SMISC_SYSCGC_CGCSEC_MASK       0x40u
#define SMISC_SYSCGC_CGCSEC_SHIFT      6u
#define SMISC_SYSCGC_CGCSEC_WIDTH      1u
#define SMISC_SYSCGC_CGCSEC(x)         (((uint32_t)(((uint32_t)(x))<<SMISC_SYSCGC_CGCSEC_SHIFT))&SMISC_SYSCGC_CGCSEC_MASK)
#define SMISC_SYSCGC_CGCINTM_MASK      0x20u
#define SMISC_SYSCGC_CGCINTM_SHIFT     5u
#define SMISC_SYSCGC_CGCINTM_WIDTH     1u
#define SMISC_SYSCGC_CGCINTM(x)        (((uint32_t)(((uint32_t)(x))<<SMISC_SYSCGC_CGCINTM_SHIFT))&SMISC_SYSCGC_CGCINTM_MASK)
#define SMISC_SYSCGC_CGCEIM_MASK       0x10u
#define SMISC_SYSCGC_CGCEIM_SHIFT      4u
#define SMISC_SYSCGC_CGCEIM_WIDTH      1u
#define SMISC_SYSCGC_CGCEIM(x)         (((uint32_t)(((uint32_t)(x))<<SMISC_SYSCGC_CGCEIM_SHIFT))&SMISC_SYSCGC_CGCEIM_MASK)
#define SMISC_SYSCGC_CGCERM_MASK       0x8u
#define SMISC_SYSCGC_CGCERM_SHIFT      3u
#define SMISC_SYSCGC_CGCERM_WIDTH      1u
#define SMISC_SYSCGC_CGCERM(x)         (((uint32_t)(((uint32_t)(x))<<SMISC_SYSCGC_CGCERM_SHIFT))&SMISC_SYSCGC_CGCERM_MASK)
#define SMISC_SYSCGC_CGCDMA_MASK       0x4u
#define SMISC_SYSCGC_CGCDMA_SHIFT      2u
#define SMISC_SYSCGC_CGCDMA_WIDTH      1u
#define SMISC_SYSCGC_CGCDMA(x)         (((uint32_t)(((uint32_t)(x))<<SMISC_SYSCGC_CGCDMA_SHIFT))&SMISC_SYSCGC_CGCDMA_MASK)
#define SMISC_SYSCGC_CGCMAP_MASK       0x2u
#define SMISC_SYSCGC_CGCMAP_SHIFT      1u
#define SMISC_SYSCGC_CGCMAP_WIDTH      1u
#define SMISC_SYSCGC_CGCMAP(x)         (((uint32_t)(((uint32_t)(x))<<SMISC_SYSCGC_CGCMAP_SHIFT))&SMISC_SYSCGC_CGCMAP_MASK)
#define SMISC_SYSCGC_CGCROM_MASK       0x1u
#define SMISC_SYSCGC_CGCROM_SHIFT      0u
#define SMISC_SYSCGC_CGCROM_WIDTH      1u
#define SMISC_SYSCGC_CGCROM(x)         (((uint32_t)(((uint32_t)(x))<<SMISC_SYSCGC_CGCROM_SHIFT))&SMISC_SYSCGC_CGCROM_MASK)
/* SYSCGC Reg Mask */
#define SMISC_SYSCGC_MASK              0x000000FFu
/* UID3 Bit Fields */
#define SMISC_UID3_UID127_96_MASK      0xFFFFFFFFu
#define SMISC_UID3_UID127_96_SHIFT     0u
#define SMISC_UID3_UID127_96_WIDTH     32u
#define SMISC_UID3_UID127_96(x)        (((uint32_t)(((uint32_t)(x))<<SMISC_UID3_UID127_96_SHIFT))&SMISC_UID3_UID127_96_MASK)
/* UID3 Reg Mask */
#define SMISC_UID3_MASK                0xFFFFFFFFu
/* UID2 Bit Fields */
#define SMISC_UID2_UID95_64_MASK       0xFFFFFFFFu
#define SMISC_UID2_UID95_64_SHIFT      0u
#define SMISC_UID2_UID95_64_WIDTH      32u
#define SMISC_UID2_UID95_64(x)         (((uint32_t)(((uint32_t)(x))<<SMISC_UID2_UID95_64_SHIFT))&SMISC_UID2_UID95_64_MASK)
/* UID2 Reg Mask */
#define SMISC_UID2_MASK                0xFFFFFFFFu
/* UID1 Bit Fields */
#define SMISC_UID1_UID63_32_MASK       0xFFFFFFFFu
#define SMISC_UID1_UID63_32_SHIFT      0u
#define SMISC_UID1_UID63_32_WIDTH      32u
#define SMISC_UID1_UID63_32(x)         (((uint32_t)(((uint32_t)(x))<<SMISC_UID1_UID63_32_SHIFT))&SMISC_UID1_UID63_32_MASK)
/* UID1 Reg Mask */
#define SMISC_UID1_MASK                0xFFFFFFFFu
/* UID0 Bit Fields */
#define SMISC_UID0_UID31_0_MASK        0xFFFFFFFFu
#define SMISC_UID0_UID31_0_SHIFT       0u
#define SMISC_UID0_UID31_0_WIDTH       32u
#define SMISC_UID0_UID31_0(x)          (((uint32_t)(((uint32_t)(x))<<SMISC_UID0_UID31_0_SHIFT))&SMISC_UID0_UID31_0_MASK)
/* UID0 Reg Mask */
#define SMISC_UID0_MASK                0xFFFFFFFFu
/* TRACECLKDIV Bit Fields */
#define SMISC_TRACECLKDIV_TRACEDIVEN_MASK 0x10000000u
#define SMISC_TRACECLKDIV_TRACEDIVEN_SHIFT 28u
#define SMISC_TRACECLKDIV_TRACEDIVEN_WIDTH 1u
#define SMISC_TRACECLKDIV_TRACEDIVEN(x) (((uint32_t)(((uint32_t)(x))<<SMISC_TRACECLKDIV_TRACEDIVEN_SHIFT))&SMISC_TRACECLKDIV_TRACEDIVEN_MASK)
#define SMISC_TRACECLKDIV_TRACEDIV_MASK 0xEu
#define SMISC_TRACECLKDIV_TRACEDIV_SHIFT 1u
#define SMISC_TRACECLKDIV_TRACEDIV_WIDTH 3u
#define SMISC_TRACECLKDIV_TRACEDIV(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_TRACECLKDIV_TRACEDIV_SHIFT))&SMISC_TRACECLKDIV_TRACEDIV_MASK)
#define SMISC_TRACECLKDIV_TRACEFRAC_MASK 0x1u
#define SMISC_TRACECLKDIV_TRACEFRAC_SHIFT 0u
#define SMISC_TRACECLKDIV_TRACEFRAC_WIDTH 1u
#define SMISC_TRACECLKDIV_TRACEFRAC(x) (((uint32_t)(((uint32_t)(x))<<SMISC_TRACECLKDIV_TRACEFRAC_SHIFT))&SMISC_TRACECLKDIV_TRACEFRAC_MASK)
/* TRACECLKDIV Reg Mask */
#define SMISC_TRACECLKDIV_MASK         0x1000000Fu
/* SOFTCTRL Bit Fields */
#define SMISC_SOFTCTRL_SWINT_MASK      0x80000000u
#define SMISC_SOFTCTRL_SWINT_SHIFT     31u
#define SMISC_SOFTCTRL_SWINT_WIDTH     1u
#define SMISC_SOFTCTRL_SWINT(x)        (((uint32_t)(((uint32_t)(x))<<SMISC_SOFTCTRL_SWINT_SHIFT))&SMISC_SOFTCTRL_SWINT_MASK)
#define SMISC_SOFTCTRL_SWTRG7_MASK     0x80u
#define SMISC_SOFTCTRL_SWTRG7_SHIFT    7u
#define SMISC_SOFTCTRL_SWTRG7_WIDTH    1u
#define SMISC_SOFTCTRL_SWTRG7(x)       (((uint32_t)(((uint32_t)(x))<<SMISC_SOFTCTRL_SWTRG7_SHIFT))&SMISC_SOFTCTRL_SWTRG7_MASK)
#define SMISC_SOFTCTRL_SWTRG6_MASK     0x40u
#define SMISC_SOFTCTRL_SWTRG6_SHIFT    6u
#define SMISC_SOFTCTRL_SWTRG6_WIDTH    1u
#define SMISC_SOFTCTRL_SWTRG6(x)       (((uint32_t)(((uint32_t)(x))<<SMISC_SOFTCTRL_SWTRG6_SHIFT))&SMISC_SOFTCTRL_SWTRG6_MASK)
#define SMISC_SOFTCTRL_SWTRG5_MASK     0x20u
#define SMISC_SOFTCTRL_SWTRG5_SHIFT    5u
#define SMISC_SOFTCTRL_SWTRG5_WIDTH    1u
#define SMISC_SOFTCTRL_SWTRG5(x)       (((uint32_t)(((uint32_t)(x))<<SMISC_SOFTCTRL_SWTRG5_SHIFT))&SMISC_SOFTCTRL_SWTRG5_MASK)
#define SMISC_SOFTCTRL_SWTRG4_MASK     0x10u
#define SMISC_SOFTCTRL_SWTRG4_SHIFT    4u
#define SMISC_SOFTCTRL_SWTRG4_WIDTH    1u
#define SMISC_SOFTCTRL_SWTRG4(x)       (((uint32_t)(((uint32_t)(x))<<SMISC_SOFTCTRL_SWTRG4_SHIFT))&SMISC_SOFTCTRL_SWTRG4_MASK)
#define SMISC_SOFTCTRL_SWTRG3_MASK     0x8u
#define SMISC_SOFTCTRL_SWTRG3_SHIFT    3u
#define SMISC_SOFTCTRL_SWTRG3_WIDTH    1u
#define SMISC_SOFTCTRL_SWTRG3(x)       (((uint32_t)(((uint32_t)(x))<<SMISC_SOFTCTRL_SWTRG3_SHIFT))&SMISC_SOFTCTRL_SWTRG3_MASK)
#define SMISC_SOFTCTRL_SWTRG2_MASK     0x4u
#define SMISC_SOFTCTRL_SWTRG2_SHIFT    2u
#define SMISC_SOFTCTRL_SWTRG2_WIDTH    1u
#define SMISC_SOFTCTRL_SWTRG2(x)       (((uint32_t)(((uint32_t)(x))<<SMISC_SOFTCTRL_SWTRG2_SHIFT))&SMISC_SOFTCTRL_SWTRG2_MASK)
#define SMISC_SOFTCTRL_SWTRG1_MASK     0x2u
#define SMISC_SOFTCTRL_SWTRG1_SHIFT    1u
#define SMISC_SOFTCTRL_SWTRG1_WIDTH    1u
#define SMISC_SOFTCTRL_SWTRG1(x)       (((uint32_t)(((uint32_t)(x))<<SMISC_SOFTCTRL_SWTRG1_SHIFT))&SMISC_SOFTCTRL_SWTRG1_MASK)
#define SMISC_SOFTCTRL_SWTRG0_MASK     0x1u
#define SMISC_SOFTCTRL_SWTRG0_SHIFT    0u
#define SMISC_SOFTCTRL_SWTRG0_WIDTH    1u
#define SMISC_SOFTCTRL_SWTRG0(x)       (((uint32_t)(((uint32_t)(x))<<SMISC_SOFTCTRL_SWTRG0_SHIFT))&SMISC_SOFTCTRL_SWTRG0_MASK)
/* SOFTCTRL Reg Mask */
#define SMISC_SOFTCTRL_MASK            0x800000FFu
/* STATCTRL Bit Fields */
#define SMISC_STATCTRL_ENET_CHID_MASK  0x3u
#define SMISC_STATCTRL_ENET_CHID_SHIFT 0u
#define SMISC_STATCTRL_ENET_CHID_WIDTH 2u
#define SMISC_STATCTRL_ENET_CHID(x)    (((uint32_t)(((uint32_t)(x))<<SMISC_STATCTRL_ENET_CHID_SHIFT))&SMISC_STATCTRL_ENET_CHID_MASK)
/* STATCTRL Reg Mask */
#define SMISC_STATCTRL_MASK            0x00000003u
/* RNGCNTR Bit Fields */
#define SMISC_RNGCNTR_RNGCOUNT_MASK    0xFFFFu
#define SMISC_RNGCNTR_RNGCOUNT_SHIFT   0u
#define SMISC_RNGCNTR_RNGCOUNT_WIDTH   16u
#define SMISC_RNGCNTR_RNGCOUNT(x)      (((uint32_t)(((uint32_t)(x))<<SMISC_RNGCNTR_RNGCOUNT_SHIFT))&SMISC_RNGCNTR_RNGCOUNT_MASK)
/* RNGCNTR Reg Mask */
#define SMISC_RNGCNTR_MASK             0x0000FFFFu
/* PERIMUX0 Bit Fields */
#define SMISC_PERIMUX0_FCSPI3_MON_MASK 0x3000u
#define SMISC_PERIMUX0_FCSPI3_MON_SHIFT 12u
#define SMISC_PERIMUX0_FCSPI3_MON_WIDTH 2u
#define SMISC_PERIMUX0_FCSPI3_MON(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_PERIMUX0_FCSPI3_MON_SHIFT))&SMISC_PERIMUX0_FCSPI3_MON_MASK)
#define SMISC_PERIMUX0_FCSPI2_MON_MASK 0x300u
#define SMISC_PERIMUX0_FCSPI2_MON_SHIFT 8u
#define SMISC_PERIMUX0_FCSPI2_MON_WIDTH 2u
#define SMISC_PERIMUX0_FCSPI2_MON(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_PERIMUX0_FCSPI2_MON_SHIFT))&SMISC_PERIMUX0_FCSPI2_MON_MASK)
#define SMISC_PERIMUX0_FCSPI1_MON_MASK 0x30u
#define SMISC_PERIMUX0_FCSPI1_MON_SHIFT 4u
#define SMISC_PERIMUX0_FCSPI1_MON_WIDTH 2u
#define SMISC_PERIMUX0_FCSPI1_MON(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_PERIMUX0_FCSPI1_MON_SHIFT))&SMISC_PERIMUX0_FCSPI1_MON_MASK)
#define SMISC_PERIMUX0_FCSPI0_MON_MASK 0x3u
#define SMISC_PERIMUX0_FCSPI0_MON_SHIFT 0u
#define SMISC_PERIMUX0_FCSPI0_MON_WIDTH 2u
#define SMISC_PERIMUX0_FCSPI0_MON(x)   (((uint32_t)(((uint32_t)(x))<<SMISC_PERIMUX0_FCSPI0_MON_SHIFT))&SMISC_PERIMUX0_FCSPI0_MON_MASK)
/* PERIMUX0 Reg Mask */
#define SMISC_PERIMUX0_MASK            0x00003333u
/* PERIMUX1 Bit Fields */
#define SMISC_PERIMUX1_FCUART5_MON_MASK 0x700000u
#define SMISC_PERIMUX1_FCUART5_MON_SHIFT 20u
#define SMISC_PERIMUX1_FCUART5_MON_WIDTH 3u
#define SMISC_PERIMUX1_FCUART5_MON(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERIMUX1_FCUART5_MON_SHIFT))&SMISC_PERIMUX1_FCUART5_MON_MASK)
#define SMISC_PERIMUX1_FCUART4_MON_MASK 0x70000u
#define SMISC_PERIMUX1_FCUART4_MON_SHIFT 16u
#define SMISC_PERIMUX1_FCUART4_MON_WIDTH 3u
#define SMISC_PERIMUX1_FCUART4_MON(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERIMUX1_FCUART4_MON_SHIFT))&SMISC_PERIMUX1_FCUART4_MON_MASK)
#define SMISC_PERIMUX1_FCUART3_MON_MASK 0x7000u
#define SMISC_PERIMUX1_FCUART3_MON_SHIFT 12u
#define SMISC_PERIMUX1_FCUART3_MON_WIDTH 3u
#define SMISC_PERIMUX1_FCUART3_MON(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERIMUX1_FCUART3_MON_SHIFT))&SMISC_PERIMUX1_FCUART3_MON_MASK)
#define SMISC_PERIMUX1_FCUART2_MON_MASK 0x700u
#define SMISC_PERIMUX1_FCUART2_MON_SHIFT 8u
#define SMISC_PERIMUX1_FCUART2_MON_WIDTH 3u
#define SMISC_PERIMUX1_FCUART2_MON(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERIMUX1_FCUART2_MON_SHIFT))&SMISC_PERIMUX1_FCUART2_MON_MASK)
#define SMISC_PERIMUX1_FCUART1_MON_MASK 0x70u
#define SMISC_PERIMUX1_FCUART1_MON_SHIFT 4u
#define SMISC_PERIMUX1_FCUART1_MON_WIDTH 3u
#define SMISC_PERIMUX1_FCUART1_MON(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERIMUX1_FCUART1_MON_SHIFT))&SMISC_PERIMUX1_FCUART1_MON_MASK)
#define SMISC_PERIMUX1_FCUART0_MON_MASK 0x7u
#define SMISC_PERIMUX1_FCUART0_MON_SHIFT 0u
#define SMISC_PERIMUX1_FCUART0_MON_WIDTH 3u
#define SMISC_PERIMUX1_FCUART0_MON(x)  (((uint32_t)(((uint32_t)(x))<<SMISC_PERIMUX1_FCUART0_MON_SHIFT))&SMISC_PERIMUX1_FCUART0_MON_MASK)
/* PERIMUX1 Reg Mask */
#define SMISC_PERIMUX1_MASK            0x00777777u
/* STOPMODE0 Bit Fields */
#define SMISC_STOPMODE0_ADC0_STOP_ACK_MASK 0x8000000u
#define SMISC_STOPMODE0_ADC0_STOP_ACK_SHIFT 27u
#define SMISC_STOPMODE0_ADC0_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE0_ADC0_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE0_ADC0_STOP_ACK_SHIFT))&SMISC_STOPMODE0_ADC0_STOP_ACK_MASK)
#define SMISC_STOPMODE0_FCSPI3_STOP_ACK_MASK 0x8000u
#define SMISC_STOPMODE0_FCSPI3_STOP_ACK_SHIFT 15u
#define SMISC_STOPMODE0_FCSPI3_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE0_FCSPI3_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE0_FCSPI3_STOP_ACK_SHIFT))&SMISC_STOPMODE0_FCSPI3_STOP_ACK_MASK)
#define SMISC_STOPMODE0_FCSPI2_STOP_ACK_MASK 0x4000u
#define SMISC_STOPMODE0_FCSPI2_STOP_ACK_SHIFT 14u
#define SMISC_STOPMODE0_FCSPI2_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE0_FCSPI2_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE0_FCSPI2_STOP_ACK_SHIFT))&SMISC_STOPMODE0_FCSPI2_STOP_ACK_MASK)
#define SMISC_STOPMODE0_FCSPI1_STOP_ACK_MASK 0x2000u
#define SMISC_STOPMODE0_FCSPI1_STOP_ACK_SHIFT 13u
#define SMISC_STOPMODE0_FCSPI1_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE0_FCSPI1_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE0_FCSPI1_STOP_ACK_SHIFT))&SMISC_STOPMODE0_FCSPI1_STOP_ACK_MASK)
#define SMISC_STOPMODE0_FCSPI0_STOP_ACK_MASK 0x1000u
#define SMISC_STOPMODE0_FCSPI0_STOP_ACK_SHIFT 12u
#define SMISC_STOPMODE0_FCSPI0_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE0_FCSPI0_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE0_FCSPI0_STOP_ACK_SHIFT))&SMISC_STOPMODE0_FCSPI0_STOP_ACK_MASK)
#define SMISC_STOPMODE0_ADC1_STOP_ACK_MASK 0x80u
#define SMISC_STOPMODE0_ADC1_STOP_ACK_SHIFT 7u
#define SMISC_STOPMODE0_ADC1_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE0_ADC1_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE0_ADC1_STOP_ACK_SHIFT))&SMISC_STOPMODE0_ADC1_STOP_ACK_MASK)
/* STOPMODE0 Reg Mask */
#define SMISC_STOPMODE0_MASK           0x0800F080u
/* STOPMODE1 Bit Fields */
#define SMISC_STOPMODE1_FCUART5_STOP_ACK_MASK 0x20000000u
#define SMISC_STOPMODE1_FCUART5_STOP_ACK_SHIFT 29u
#define SMISC_STOPMODE1_FCUART5_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE1_FCUART5_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE1_FCUART5_STOP_ACK_SHIFT))&SMISC_STOPMODE1_FCUART5_STOP_ACK_MASK)
#define SMISC_STOPMODE1_FCUART4_STOP_ACK_MASK 0x10000000u
#define SMISC_STOPMODE1_FCUART4_STOP_ACK_SHIFT 28u
#define SMISC_STOPMODE1_FCUART4_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE1_FCUART4_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE1_FCUART4_STOP_ACK_SHIFT))&SMISC_STOPMODE1_FCUART4_STOP_ACK_MASK)
#define SMISC_STOPMODE1_FCUART3_STOP_ACK_MASK 0x8000000u
#define SMISC_STOPMODE1_FCUART3_STOP_ACK_SHIFT 27u
#define SMISC_STOPMODE1_FCUART3_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE1_FCUART3_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE1_FCUART3_STOP_ACK_SHIFT))&SMISC_STOPMODE1_FCUART3_STOP_ACK_MASK)
#define SMISC_STOPMODE1_I2S1_STOP_ACK_MASK 0x200000u
#define SMISC_STOPMODE1_I2S1_STOP_ACK_SHIFT 21u
#define SMISC_STOPMODE1_I2S1_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE1_I2S1_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE1_I2S1_STOP_ACK_SHIFT))&SMISC_STOPMODE1_I2S1_STOP_ACK_MASK)
#define SMISC_STOPMODE1_I2S0_STOP_ACK_MASK 0x100000u
#define SMISC_STOPMODE1_I2S0_STOP_ACK_SHIFT 20u
#define SMISC_STOPMODE1_I2S0_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE1_I2S0_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE1_I2S0_STOP_ACK_SHIFT))&SMISC_STOPMODE1_I2S0_STOP_ACK_MASK)
/* STOPMODE1 Reg Mask */
#define SMISC_STOPMODE1_MASK           0x38300000u
/* STOPMODE2 Bit Fields */
#define SMISC_STOPMODE2_TMU0_STOP_ACK_MASK 0x8000000u
#define SMISC_STOPMODE2_TMU0_STOP_ACK_SHIFT 27u
#define SMISC_STOPMODE2_TMU0_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE2_TMU0_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE2_TMU0_STOP_ACK_SHIFT))&SMISC_STOPMODE2_TMU0_STOP_ACK_MASK)
#define SMISC_STOPMODE2_FCUART2_STOP_ACK_MASK 0x1000u
#define SMISC_STOPMODE2_FCUART2_STOP_ACK_SHIFT 12u
#define SMISC_STOPMODE2_FCUART2_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE2_FCUART2_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE2_FCUART2_STOP_ACK_SHIFT))&SMISC_STOPMODE2_FCUART2_STOP_ACK_MASK)
#define SMISC_STOPMODE2_FCUART1_STOP_ACK_MASK 0x800u
#define SMISC_STOPMODE2_FCUART1_STOP_ACK_SHIFT 11u
#define SMISC_STOPMODE2_FCUART1_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE2_FCUART1_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE2_FCUART1_STOP_ACK_SHIFT))&SMISC_STOPMODE2_FCUART1_STOP_ACK_MASK)
#define SMISC_STOPMODE2_FCUART0_STOP_ACK_MASK 0x400u
#define SMISC_STOPMODE2_FCUART0_STOP_ACK_SHIFT 10u
#define SMISC_STOPMODE2_FCUART0_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE2_FCUART0_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE2_FCUART0_STOP_ACK_SHIFT))&SMISC_STOPMODE2_FCUART0_STOP_ACK_MASK)
#define SMISC_STOPMODE2_FCIIC1_STOP_ACK_MASK 0x80u
#define SMISC_STOPMODE2_FCIIC1_STOP_ACK_SHIFT 7u
#define SMISC_STOPMODE2_FCIIC1_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE2_FCIIC1_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE2_FCIIC1_STOP_ACK_SHIFT))&SMISC_STOPMODE2_FCIIC1_STOP_ACK_MASK)
#define SMISC_STOPMODE2_FCIIC0_STOP_ACK_MASK 0x40u
#define SMISC_STOPMODE2_FCIIC0_STOP_ACK_SHIFT 6u
#define SMISC_STOPMODE2_FCIIC0_STOP_ACK_WIDTH 1u
#define SMISC_STOPMODE2_FCIIC0_STOP_ACK(x) (((uint32_t)(((uint32_t)(x))<<SMISC_STOPMODE2_FCIIC0_STOP_ACK_SHIFT))&SMISC_STOPMODE2_FCIIC0_STOP_ACK_MASK)
/* STOPMODE2 Reg Mask */
#define SMISC_STOPMODE2_MASK           0x08001CC0u
/**
 * @}
 */ /* end of group SMISC_Register_Masks */
/**
 * @}
 */ /* end of group SMISC_Peripheral_Access_Layer */
 
#ifdef __cplusplus
}
#endif
#endif
