/*
 * MotorDriver_Cfg.h
 *
 *  Created on: 2025年3月19日
 *      Author: 14013
 */

#ifndef BSW_CDD_MOTORDRIVER_INC_MOTORDRIVER_CFG_H_
#define BSW_CDD_MOTORDRIVER_INC_MOTORDRIVER_CFG_H_

#include "MotorDriver_Type.h"

#define GENCTRL1_ADDR 0x00
#define GENCTRL2_ADDR 0x01
#define VDS1_ADDR 0x02
#define CCP_BLK1_ADDR 0x04
#define CCP_BLK2_ACT_REG_BANK_0_ADDR 0x05
#define CCP_BLK2_FW_REG_BANK_1_ADDR 0x05
#define HBMODE_ADDR 0x06
#define PWMSET_REG_BANK_0_ADDR 0x07
#define TPRECHG_ADDR 0x08
#define HBIDIAG_ADDR 0x09
#define ST_ICHG_REG_BANK_0_ADDR 0x0A
#define PWM_PCHG_INIT_REG_BANK_1_ADDR 0x0A
#define PWM_ICHG_ACT_REG_BANK_0_ADDR 0x0B
#define PWM_ICHG_FW_REG_BANK_1_ADDR 0x0B
#define PWM_IDCHG_ACT_REG_BANK_0_ADDR 0x0C
#define PWM_PDCHG_INIT_REG_BANK_1_ADDR 0x0C
#define PWM_ICHGMAX_CCP_BLK3_ACT_REG_BANK_0_ADDR 0x0D
#define PWM_ICHGMAX_CCP_BLK3_FW_REG_BANK_1_ADDR 0x0D
#define TDON_OFF1_ADDR 0x0E
#define TDON_OFF2_ADDR 0x0F
#define TDON_OFF3_ADDR 0x10
/* Status register */
#define GENSTAT_ADDR 0x11
#define DSOV_ADDR 0x12
#define HBVOUT_PWMERR_ADDR 0x13
#define EFF_TDON_OFF1_ADDR 0x14
#define EFF_TDON_OFF2_ADDR 0x15
#define EFF_TDON_OFF3_ADDR 0x16
#define TRISE_FALL1_ADDR 0x17
#define TRISE_FALL2_ADDR 0x18
#define TRISE_FALL3_ADDR 0x19
#define DEVID_ADDR 0x1F

#define INIT_SPI_MESSAGE(data, OP, address, labt, msb) {data, OP, address, labt, msb}

/**
 * @brief The TLE92104 differs from the TLE92108 by having one less VDS2 register 
 *        at address 0x03.
 */

/*
typedef enum{
    SEND_CTRL_GENCTRL1_INDEX,
    SEND_CTRL_GENCTRL2_INDEX,
    SEND_CTRL_VDS1_INDEX,
    SEND_CTRL_CCP_BLK1_INDEX,
    SEND_CTRL_CCP_BLK2_ACT_REG_BANK_0_FW_REG_BANK_1_INDEX,
    SEND_CTRL_HBMODE_INDEX,
    SEND_CTRL_PWMSET_REG_BANK_0_INDEX,
    SEND_CTRL_TPRECHG_INDEX,
    SEND_CTRL_HBIDIAG_INDEX,
    SEND_CTRL_ST_ICHG_REG_BANK_0_PWM_PCHG_INIT_REG_BANK_1_INDEX,
    SEND_CTRL_PWM_ICHG_ACT_REG_BANK_0_FW_REG_BANK_1_INDEX,
    SEND_CTRL_PWM_IDCHG_ACT_REG_BANK_0_PWM_PDCHG_INIT_REG_BANK_1_INDEX,
    SEND_CTRL_PWM_ICHGMAX_CCP_BLK3_ACT_REG_BANK_0_FW_REG_BANK_1_INDEX,
    SEND_CTRL_TDON_OFF1_INDEX,
    SEND_CTRL_TDON_OFF2_INDEX,
    SEND_CTRL_TDON_OFF3_INDEX,
    TLE9210X_CTRL_REG_COUNT
}TLE92104_CTRL_Registers_Send_Index;*/

typedef enum{
    BANK0_CTRL_GENCTRL1_INDEX,
    BANK0_CTRL_GENCTRL2_INDEX,
    BANK0_CTRL_VDS1_INDEX,
    BANK0_CTRL_CCP_BLK1_INDEX,
    BANK0_CTRL_CCP_BLK2_ACT_REG_BANK_0_FW_REG_BANK_1_INDEX,
    BANK0_CTRL_HBMODE_INDEX,
    BANK0_CTRL_PWMSET_REG_BANK_0_INDEX,
    BANK0_CTRL_TPRECHG_INDEX,
    BANK0_CTRL_HBIDIAG_INDEX,
    BANK0_CTRL_ST_ICHG_REG_BANK_0_PWM_PCHG_INIT_REG_BANK_1_INDEX,
    BANK0_CTRL_PWM_ICHG_ACT_REG_BANK_0_FW_REG_BANK_1_INDEX,
    BANK0_CTRL_PWM_IDCHG_ACT_REG_BANK_0_PWM_PDCHG_INIT_REG_BANK_1_INDEX,
    BANK0_CTRL_PWM_ICHGMAX_CCP_BLK3_ACT_REG_BANK_0_FW_REG_BANK_1_INDEX,
    BANK0_CTRL_TDON_OFF1_INDEX,
    BANK0_CTRL_TDON_OFF2_INDEX,
    BANK0_CTRL_TDON_OFF3_INDEX,
    TLE92104_BANK0_CTRL_Registers_Send_Count
}TLE92104_BANK0_CTRL_Registers_Send_Index;

typedef enum{
    BANK1_CTRL_GENCTRL1_INDEX,
    BANK1_CTRL_GENCTRL2_INDEX,
    BANK1_CTRL_VDS1_INDEX,
    BANK1_CTRL_CCP_BLK1_INDEX,
    BANK1_CTRL_CCP_BLK2_ACT_REG_BANK_0_FW_REG_BANK_1_INDEX,
    BANK1_CTRL_HBMODE_INDEX,
    BANK1_CTRL_TPRECHG_INDEX,
    BANK1_CTRL_HBIDIAG_INDEX,
    BANK1_CTRL_ST_ICHG_REG_BANK_0_PWM_PCHG_INIT_REG_BANK_1_INDEX,
    BANK1_CTRL_PWM_ICHG_ACT_REG_BANK_0_FW_REG_BANK_1_INDEX,
    BANK1_CTRL_PWM_IDCHG_ACT_REG_BANK_0_PWM_PDCHG_INIT_REG_BANK_1_INDEX,
    BANK1_CTRL_PWM_ICHGMAX_CCP_BLK3_ACT_REG_BANK_0_FW_REG_BANK_1_INDEX,
    BANK1_CTRL_TDON_OFF1_INDEX,
    BANK1_CTRL_TDON_OFF2_INDEX,
    BANK1_CTRL_TDON_OFF3_INDEX,
    TLE92104_BANK1_CTRL_Registers_Send_Count
}TLE92104_BANK1_CTRL_Registers_Send_Index;

typedef enum {
    All_CTRL_GENCTRL1_INDEX,
    All_CTRL_GENCTRL2_INDEX,
    All_CTRL_VDS1_INDEX,
    All_CTRL_CCP_BLK1_INDEX,
    All_CTRL_CCP_BLK2_ACT_REG_BANK_0_INDEX,
    All_CTRL_CCP_BLK2_FW_REG_BANK_1_INDEX,
    All_CTRL_HBMODE_INDEX,
    All_CTRL_PWMSET_REG_BANK_0_INDEX,
    All_CTRL_TPRECHG_INDEX,
    All_CTRL_HBIDIAG_INDEX,
    All_CTRL_ST_ICHG_REG_BANK_0_INDEX,
    All_CTRL_PWM_PCHG_INIT_REG_BANK_1_INDEX,
    All_CTRL_PWM_ICHG_ACT_REG_BANK_0_INDEX,
    All_CTRL_PWM_ICHG_FW_REG_BANK_1_INDEX,
    All_CTRL_PWM_IDCHG_ACT_REG_BANK_0_INDEX,
    All_CTRL_PWM_PDCHG_INIT_REG_BANK_1_INDEX,
    All_CTRL_PWM_ICHGMAX_CCP_BLK3_ACT_REG_BANK_0_INDEX,
    All_CTRL_PWM_ICHGMAX_CCP_BLK3_FW_REG_BANK_1_INDEX,
    All_CTRL_TDON_OFF1_INDEX,
    All_CTRL_TDON_OFF2_INDEX,
    All_CTRL_TDON_OFF3_INDEX,
    TLE92104_All_CTRL_REG_COUNT
} TLE92104_All_CTRL_Registers_Restore_Index;

typedef enum {
    All_STAT_GENSTAT_INDEX,
    All_STAT_DSOV_INDEX,
    All_STAT_HBVOUT_PWMERR_INDEX,
    All_STAT_EFF_TDON_OFF1_INDEX,
    All_STAT_EFF_TDON_OFF2_INDEX,
    All_STAT_EFF_TDON_OFF3_INDEX,
    All_STAT_TRISE_FALL1_INDEX,
    All_STAT_TRISE_FALL2_INDEX,
    All_STAT_TRISE_FALL3_INDEX,
    All_STAT_DEVID_INDEX,
    TLE92104_All_STAT_REG_COUNT
} TLE92104_All_STAT_Registers_Restore_Index;

typedef enum {
    Usual_Use_CTRL_GENCTRL1_INDEX,
    Usual_Use_CTRL_GENCTRL2_INDEX,
    Usual_Use_CTRL_VDS1_INDEX,
    Usual_Use_CTRL_HBMODE_INDEX,
    Usual_Use_CTRL_HBIDIAG_INDEX,
    Usual_Use_STAT_GENSTAT_INDEX,
    Usual_Use_STAT_DSOV_INDEX,
    TLE92104_Usual_Use_CTRL_Registers_Count
} TLE92104_Usual_Use_CTRL_Registers_Send_Index;

extern TLE9210X_SPI_Frame TLE92104_All_CTRL_REG_SPI_Frame_Table[TLE92104_All_CTRL_REG_COUNT];
extern TLE9210X_SPI_Frame TLE92104_All_STAT_REG_SPI_Frame_Table[TLE92104_All_STAT_REG_COUNT];
extern TLE9210X_SPI_Frame TLE92104_Usual_Use_CTRL_REG_SPI_Frame_Table[TLE92104_Usual_Use_CTRL_Registers_Count];


void TLE92108_SpiInit(void);
FCSPI_StatusType TLE92108_SpiSendSync(uint8_t *pTxData,uint8_t *pRxData,uint16_t u16Len);
FCSPI_StatusType TLE92108_SpiSendAsync(uint8_t *pTxData,uint8_t *pRxData,uint16_t u16Len);
#endif /* BSW_CDD_MOTORDRIVER_INC_MOTORDRIVER_CFG_H_ */
