#ifndef _DEVICE_FEATURES_FC4150F1M__A_TRGSEL_COMMON_H_
#define _DEVICE_FEATURES_FC4150F1M__A_TRGSEL_COMMON_H_
/*********************** Trgsel Features ****************************/
#define TRGSEL_INSTANCE_COUNT                                  (4u)
/** Peripheral TRGSEL3 base address */
#define TRGSEL3_BASE                             (0x40072000u)
/** Peripheral TRGSEL3 base pointer */
#define TRGSEL3                                  ((TRGSEL_Type *)TRGSEL3_BASE)
/** Array initializer of TRGSEL peripheral base addresses */
#define TRGSEL_BASE_ADDRS                        {TRGSEL0_BASE, TRGSEL1_BASE, TRGSEL2_BASE, TRGSEL3_BASE}
/** Array initializer of TRGSEL peripheral base pointers */
#define TRGSEL_BASE_PTRS                         {TRGSEL0, TRGSEL1, TRGSEL2, TRGSEL3}

/**
 * @brief TrgSel instance 0 trigger targets
 *
 */
typedef enum
{
    TRGSEL0_TARGET_FTU0_TRG0               = 0U,
    TRGSEL0_TARGET_FTU1_TRG0               = 1U,
    TRGSEL0_TARGET_FTU2_TRG0               = 2U,
    TRGSEL0_TARGET_FTU3_TRG0               = 3U,
    TRGSEL0_TARGET_FTU4_TRG0               = 4U,
    TRGSEL0_TARGET_FTU5_TRG0               = 5U,
    TRGSEL0_TARGET_PTIMER0_TRG0            = 6U,
    TRGSEL0_TARGET_PTIMER1_TRG0            = 7U,
    TRGSEL0_TARGET_FCPIT_TRG_CH0           = 12U,
    TRGSEL0_TARGET_FCPIT_TRG_CH1           = 13U,
    TRGSEL0_TARGET_FCPIT_TRG_CH2           = 14U,
    TRGSEL0_TARGET_FCPIT_TRG_CH3           = 15U,
    TRGSEL0_TARGET_AOTMR0_ALT0             = 16U,
    TRGSEL0_TARGET_LU0_INPUT0A             = 17U,
    TRGSEL0_TARGET_LU0_INPUT0B             = 18U,
    TRGSEL0_TARGET_LU0_INPUT0C             = 19U,
    TRGSEL0_TARGET_LU0_INPUT0D             = 20U,
    TRGSEL0_TARGET_LU0_INPUT1A             = 21U,
    TRGSEL0_TARGET_LU0_INPUT1B             = 22U,
    TRGSEL0_TARGET_LU0_INPUT1C             = 23U,
    TRGSEL0_TARGET_LU0_INPUT1D             = 24U,
    TRGSEL0_TARGET_LU0_INPUT2A             = 25U,
    TRGSEL0_TARGET_LU0_INPUT2B             = 26U,
    TRGSEL0_TARGET_LU0_INPUT2C             = 27U,
    TRGSEL0_TARGET_LU0_INPUT2D             = 28U,
    TRGSEL0_TARGET_LU0_INPUT3A             = 29U,
    TRGSEL0_TARGET_LU0_INPUT3B             = 30U,
    TRGSEL0_TARGET_LU0_INPUT3C             = 31U,
    TRGSEL0_TARGET_LU0_INPUT3D             = 32U,
    TRGSEL0_TARGET_ADC0_TRG0               = 33U,
    TRGSEL0_TARGET_ADC0_TRG1               = 34U,
    TRGSEL0_TARGET_ADC0_TRG2               = 35U,
    TRGSEL0_TARGET_ADC0_TRG3               = 36U,
    TRGSEL0_TARGET_ADC1_TRG0               = 37U,
    TRGSEL0_TARGET_ADC1_TRG1               = 38U,
    TRGSEL0_TARGET_ADC1_TRG2               = 39U,
    TRGSEL0_TARGET_ADC1_TRG3               = 40U,
    TRGSEL0_TARGET_CMP0_SAMPLE_EN          = 41U,
    TRGSEL0_TARGET_CMP1_SAMPLE_EN          = 42U,
    TRGSEL0_TARGET_CMP2_SAMPLE_EN          = 43U,
    TRGSEL0_TARGET_TRGSEL1_INPUT0          = 44U,
    TRGSEL0_TARGET_TRGSEL1_INPUT1          = 45U,
    TRGSEL0_TARGET_TRGSEL1_INPUT2          = 46U,
    TRGSEL0_TARGET_TRGSEL1_INPUT3          = 47U,
    TRGSEL0_TARGET_FTU6_TRG0               = 52U,
    TRGSEL0_TARGET_FTU7_TRG0               = 53U
} TrgSel0_TargetType;

/**
 * @brief TrgSel instance 1 trigger targets
 *
 */
typedef enum
{
    TRGSEL1_TARGET_DMA_CH0                 = 0U,
    TRGSEL1_TARGET_DMA_CH1                 = 1U,
    TRGSEL1_TARGET_DMA_CH2                 = 2U,
    TRGSEL1_TARGET_DMA_CH3                 = 3U,
    TRGSEL1_TARGET_TRGSEL_OUT0             = 4U,
    TRGSEL1_TARGET_TRGSEL_OUT1             = 5U,
    TRGSEL1_TARGET_TRGSEL_OUT2             = 6U,
    TRGSEL1_TARGET_TRGSEL_OUT3             = 7U,
    TRGSEL1_TARGET_TRGSEL_OUT4             = 8U,
    TRGSEL1_TARGET_TRGSEL_OUT5             = 9U,
    TRGSEL1_TARGET_TRGSEL_OUT6             = 10U,
    TRGSEL1_TARGET_TRGSEL_OUT7             = 11U,
    TRGSEL1_TARGET_FCUART0_TRG             = 12U,
    TRGSEL1_TARGET_FCUART1_TRG             = 13U,
    TRGSEL1_TARGET_FCUART2_TRG             = 14U,
    TRGSEL1_TARGET_FCSPI0_TRG              = 15U,
    TRGSEL1_TARGET_FCSPI1_TRG              = 16U,
    TRGSEL1_TARGET_FCSPI2_TRG              = 17U,
    TRGSEL1_TARGET_FCIIC0_TRG              = 18U,
    TRGSEL1_TARGET_FCIIC1_TRG              = 19U,
    TRGSEL1_TARGET_HSM_TRG                 = 20U,
    TRGSEL1_TARGET_FCUART3_TRG             = 21U,
    TRGSEL1_TARGET_FCUART4_TRG             = 22U,
    TRGSEL1_TARGET_FCUART5_TRG             = 23U,
    TRGSEL1_TARGET_FCSPI3_TRG              = 24U
} TrgSel1_TargetType;

/**
 * @brief TrgSel instance 2 trigger targets
 *
 */
typedef enum
{
    TRGSEL2_TARGET_FTU0_FLT0               = 0U,
    TRGSEL2_TARGET_FTU0_FLT1               = 1U,
    TRGSEL2_TARGET_FTU0_FLT2               = 2U,
    TRGSEL2_TARGET_FTU0_FLT3               = 3U,
    TRGSEL2_TARGET_FTU1_FLT0               = 4U,
    TRGSEL2_TARGET_FTU1_FLT1               = 5U,
    TRGSEL2_TARGET_FTU1_FLT2               = 6U,
    TRGSEL2_TARGET_FTU1_FLT3               = 7U,
    TRGSEL2_TARGET_FTU2_FLT0               = 8U,
    TRGSEL2_TARGET_FTU2_FLT1               = 9U,
    TRGSEL2_TARGET_FTU2_FLT2               = 10U,
    TRGSEL2_TARGET_FTU2_FLT3               = 11U,
    TRGSEL2_TARGET_FTU3_FLT0               = 12U,
    TRGSEL2_TARGET_FTU3_FLT1               = 13U,
    TRGSEL2_TARGET_FTU3_FLT2               = 14U,
    TRGSEL2_TARGET_FTU3_FLT3               = 15U,
    TRGSEL2_TARGET_FTU4_FLT0               = 16U,
    TRGSEL2_TARGET_FTU4_FLT1               = 17U,
    TRGSEL2_TARGET_FTU5_FLT0               = 20U,
    TRGSEL2_TARGET_FTU5_FLT1               = 21U,
    TRGSEL2_TARGET_FTU0_TRG2               = 24U,
    TRGSEL2_TARGET_FTU1_TRG2               = 25U,
    TRGSEL2_TARGET_FTU2_TRG2               = 26U,
    TRGSEL2_TARGET_FTU3_TRG2               = 27U,
    TRGSEL2_TARGET_FTU4_TRG2               = 28U,
    TRGSEL2_TARGET_FTU5_TRG2               = 29U,
    TRGSEL2_TARGET_FTU6_FLT0               = 30U,
    TRGSEL2_TARGET_FTU6_FLT1               = 31U,
    TRGSEL2_TARGET_FTU6_FLT2               = 32U,
    TRGSEL2_TARGET_FTU6_FLT3               = 33U,
    TRGSEL2_TARGET_FTU7_FLT0               = 34U,
    TRGSEL2_TARGET_FTU7_FLT1               = 35U,
    TRGSEL2_TARGET_FTU7_FLT2               = 36U,
    TRGSEL2_TARGET_FTU7_FLT3               = 37U,
    TRGSEL2_TARGET_FTU6_TRG2               = 38U,
    TRGSEL2_TARGET_FTU7_TRG2               = 39U,
//    TRGSEL2_TARGET_CAN_RX                  = 40U,
} TrgSel2_TargetType;

/**
 * @brief TrgSel instance 3 trigger targets
 *
 */
typedef enum
{
    TRGSEL3_TARGET_ISM0_MON0               = 0U,
    TRGSEL3_TARGET_ISM0_MON1               = 1U,
    TRGSEL3_TARGET_ISM0_MON2               = 2U,
    TRGSEL3_TARGET_ISM0_MON3               = 3U,
    TRGSEL3_TARGET_ISM0_MON4               = 4U,
    TRGSEL3_TARGET_ISM0_MON5               = 5U,
    TRGSEL3_TARGET_ISM0_MON6               = 6U,
    TRGSEL3_TARGET_ISM0_MON7               = 7U,
    TRGSEL3_TARGET_ISM0_REF0               = 8U,
    TRGSEL3_TARGET_ISM0_REF1               = 9U,
    TRGSEL3_TARGET_ISM0_REF2               = 10U,
    TRGSEL3_TARGET_ISM0_REF3               = 11U,
    TRGSEL3_TARGET_ISM0_REF4               = 12U,
    TRGSEL3_TARGET_ISM0_REF5               = 13U,
    TRGSEL3_TARGET_ISM0_REF6               = 14U,
    TRGSEL3_TARGET_ISM0_REF7               = 15U
} TrgSel3_TargetType;

/**
 * @brief TrgSel instance 0 trigger sources
 *
 */
typedef enum
{
    TRGSEL0_SRC_VSS                        = 0U,
    TRGSEL0_SRC_VDD                        = 1U,
    TRGSEL0_SRC_SMISC_SW_TRG0              = 2U,
    TRGSEL0_SRC_SMISC_SW_TRG1              = 3U,
    TRGSEL0_SRC_SMISC_SW_TRG2              = 4U,
    TRGSEL0_SRC_SMISC_SW_TRG3              = 5U,
    TRGSEL0_SRC_TRGSEL_IN0                 = 6U,
    TRGSEL0_SRC_TRGSEL_IN1                 = 7U,
    TRGSEL0_SRC_TRGSEL_IN2                 = 8U,
    TRGSEL0_SRC_TRGSEL_IN3                 = 9U,
    TRGSEL0_SRC_TRGSEL_IN4                 = 10U,
    TRGSEL0_SRC_TRGSEL_IN5                 = 11U,
    TRGSEL0_SRC_TRGSEL_IN6                 = 12U,
    TRGSEL0_SRC_TRGSEL_IN7                 = 13U,
    TRGSEL0_SRC_TRGSEL_IN8                 = 14U,
    TRGSEL0_SRC_TRGSEL_IN9                 = 15U,
    TRGSEL0_SRC_TRGSEL_IN10                = 16U,
    TRGSEL0_SRC_TRGSEL_IN11                = 17U,
    TRGSEL0_SRC_TRGSEL_IN12                = 18U,
    TRGSEL0_SRC_TRGSEL_IN13                = 19U,
    TRGSEL0_SRC_TRGSEL_IN14                = 20U,
    TRGSEL0_SRC_CMP0_OUT                   = 22U,
    TRGSEL0_SRC_CMP1_OUT                   = 23U,
    TRGSEL0_SRC_CMP2_OUT                   = 24U,
    TRGSEL0_SRC_FCPIT_CH0                  = 25U,
    TRGSEL0_SRC_FCPIT_CH1                  = 26U,
    TRGSEL0_SRC_FCPIT_CH2                  = 27U,
    TRGSEL0_SRC_FCPIT_CH3                  = 28U,
    TRGSEL0_SRC_AONTIMER0                  = 29U,
    TRGSEL0_SRC_FTU0_RELOAD_TRG            = 30U,
    TRGSEL0_SRC_FTU0_MATCH_TRG             = 31U,
    TRGSEL0_SRC_FTU1_RELOAD_TRG            = 32U,
    TRGSEL0_SRC_FTU1_MATCH_TRG             = 33U,
    TRGSEL0_SRC_FTU2_RELOAD_TRG            = 34U,
    TRGSEL0_SRC_FTU2_MATCH_TRG             = 35U,
    TRGSEL0_SRC_FTU3_RELOAD_TRG            = 36U,
    TRGSEL0_SRC_FTU3_MATCH_TRG             = 37U,
    TRGSEL0_SRC_FTU4_RELOAD_TRG            = 38U,
    TRGSEL0_SRC_FTU4_MATCH_TRG             = 39U,
    TRGSEL0_SRC_FTU5_RELOAD_TRG            = 40U,
    TRGSEL0_SRC_FTU5_MATCH_TRG             = 41U,
    TRGSEL0_SRC_LU0_OUT0A                  = 42U,
    TRGSEL0_SRC_LU0_OUT1A                  = 43U,
    TRGSEL0_SRC_LU0_OUT2A                  = 44U,
    TRGSEL0_SRC_LU0_OUT3A                  = 45U,
    TRGSEL0_SRC_LU0_OUT0B                  = 46U,
    TRGSEL0_SRC_LU0_OUT1B                  = 47U,
    TRGSEL0_SRC_LU0_OUT2B                  = 48U,
    TRGSEL0_SRC_LU0_OUT3B                  = 49U,
    TRGSEL0_SRC_PTIMER0_ADCCH0_TRG         = 50U,
    TRGSEL0_SRC_PTIMER0_PULSE_OUT          = 51U,
    TRGSEL0_SRC_PTIMER1_ADCCH0_TRG         = 52U,
    TRGSEL0_SRC_PTIMER1_PULSE_OUT          = 53U,
    TRGSEL0_SRC_RTC_ALARM                  = 54U,
    TRGSEL0_SRC_RTC_SECOND                 = 55U,
    TRGSEL0_SRC_ADC0_COCO0                 = 60U,
    TRGSEL0_SRC_ADC0_COCO1                 = 61U,
    TRGSEL0_SRC_ADC1_COCO0                 = 62U,
    TRGSEL0_SRC_ADC1_COCO1                 = 63U,
    TRGSEL0_SRC_GPIOA_TRG                  = 64U,
    TRGSEL0_SRC_GPIOB_TRG                  = 65U,
    TRGSEL0_SRC_GPIOC_TRG                  = 66U,
    TRGSEL0_SRC_GPIOD_TRG                  = 67U,
    TRGSEL0_SRC_GPIOE_TRG                  = 68U,
    TRGSEL0_SRC_FTU0_CH0_OUT               = 69U,
    TRGSEL0_SRC_FTU0_CH1_OUT               = 70U,
    TRGSEL0_SRC_FTU0_CH2_OUT               = 71U,
    TRGSEL0_SRC_FTU0_CH3_OUT               = 72U,
    TRGSEL0_SRC_FTU0_CH4_OUT               = 73U,
    TRGSEL0_SRC_FTU0_CH5_OUT               = 74U,
    TRGSEL0_SRC_FTU0_CH6_OUT               = 75U,
    TRGSEL0_SRC_FTU0_CH7_OUT               = 76U,
    TRGSEL0_SRC_FTU1_CH0_OUT               = 77U,
    TRGSEL0_SRC_FTU1_CH1_OUT               = 78U,
    TRGSEL0_SRC_FTU1_CH2_OUT               = 79U,
    TRGSEL0_SRC_FTU1_CH3_OUT               = 80U,
    TRGSEL0_SRC_FTU1_CH4_OUT               = 81U,
    TRGSEL0_SRC_FTU1_CH5_OUT               = 82U,
    TRGSEL0_SRC_FTU1_CH6_OUT               = 83U,
    TRGSEL0_SRC_FTU1_CH7_OUT               = 84U,
    TRGSEL0_SRC_FTU2_CH0_OUT               = 85U,
    TRGSEL0_SRC_FTU2_CH1_OUT               = 86U,
    TRGSEL0_SRC_FTU2_CH2_OUT               = 87U,
    TRGSEL0_SRC_FTU2_CH3_OUT               = 88U,
    TRGSEL0_SRC_FTU2_CH4_OUT               = 89U,
    TRGSEL0_SRC_FTU2_CH5_OUT               = 90U,
    TRGSEL0_SRC_FTU2_CH6_OUT               = 91U,
    TRGSEL0_SRC_FTU2_CH7_OUT               = 92U,

//    TRGSEL0_SRC_ENET_PPS0                  = 93U,
//    TRGSEL0_SRC_ENET_PPS1                  = 94U,
//    TRGSEL0_SRC_ENET_PPS2                  = 95U,
//    TRGSEL0_SRC_ENET_PPS3                  = 96U,
    TRGSEL0_SRC_FTU6_RELOAD_TRG            = 101U,
    TRGSEL0_SRC_FTU6_MATCH_TRG             = 102U,
    TRGSEL0_SRC_FTU7_RELOAD_TRG            = 103U,
    TRGSEL0_SRC_FTU7_MATCH_TRG             = 104U
} TrgSel0_SourceType;

/**
 * @brief TrgSel instance 1 trigger sources
 *
 */
typedef enum
{
    TRGSEL1_SRC_VSS                        = 0U,
    TRGSEL1_SRC_VDD                        = 1U,
    TRGSEL1_SRC_SMISC_SW_TRG4              = 2U,
    TRGSEL1_SRC_SMISC_SW_TRG5              = 3U,
    TRGSEL1_SRC_SMISC_SW_TRG6              = 4U,
    TRGSEL1_SRC_SMISC_SW_TRG7              = 5U,
    TRGSEL1_SRC_TRGSEL_IN0                 = 6U,
    TRGSEL1_SRC_TRGSEL_IN1                 = 7U,
    TRGSEL1_SRC_TRGSEL_IN2                 = 8U,
    TRGSEL1_SRC_TRGSEL_IN3                 = 9U,
    TRGSEL1_SRC_TRGSEL_IN4                 = 10U,
    TRGSEL1_SRC_TRGSEL_IN5                 = 11U,
    TRGSEL1_SRC_TRGSEL_IN6                 = 12U,
    TRGSEL1_SRC_TRGSEL_IN7                 = 13U,
    TRGSEL1_SRC_TRGSEL_IN8                 = 14U,
    TRGSEL1_SRC_TRGSEL_IN9                 = 15U,
    TRGSEL1_SRC_TRGSEL_IN10                = 16U,
    TRGSEL1_SRC_TRGSEL_IN11                = 17U,
    TRGSEL1_SRC_TRGSEL_IN12                = 18U,
    TRGSEL1_SRC_TRGSEL_IN13                = 19U,
    TRGSEL1_SRC_TRGSEL_IN14                = 20U,
    TRGSEL1_SRC_CMP0_OUT                   = 22U,
    TRGSEL1_SRC_CMP1_OUT                   = 23U,
    TRGSEL1_SRC_CMP2_OUT                   = 24U,
    TRGSEL1_SRC_FCPIT_CH0                  = 25U,
    TRGSEL1_SRC_FCPIT_CH1                  = 26U,
    TRGSEL1_SRC_FCPIT_CH2                  = 27U,
    TRGSEL1_SRC_FCPIT_CH3                  = 28U,
    TRGSEL1_SRC_AONTIMER0                  = 29U,
    TRGSEL1_SRC_FTU0_RELOAD_TRG            = 30U,
    TRGSEL1_SRC_FTU0_MATCH_TRG             = 31U,
    TRGSEL1_SRC_FTU1_RELOAD_TRG            = 32U,
    TRGSEL1_SRC_FTU1_MATCH_TRG             = 33U,
    TRGSEL1_SRC_FTU2_RELOAD_TRG            = 34U,
    TRGSEL1_SRC_FTU2_MATCH_TRG             = 35U,
    TRGSEL1_SRC_FTU3_RELOAD_TRG            = 36U,
    TRGSEL1_SRC_FTU3_MATCH_TRG             = 37U,
    TRGSEL1_SRC_FTU4_RELOAD_TRG            = 38U,
    TRGSEL1_SRC_FTU4_MATCH_TRG             = 39U,
    TRGSEL1_SRC_FTU5_RELOAD_TRG            = 40U,
    TRGSEL1_SRC_FTU5_MATCH_TRG             = 41U,
    TRGSEL1_SRC_LU_OUT0A                   = 42U,
    TRGSEL1_SRC_LU_OUT1A                   = 43U,
    TRGSEL1_SRC_LU_OUT2A                   = 44U,
    TRGSEL1_SRC_LU_OUT3A                   = 45U,
    TRGSEL1_SRC_LU_OUT0B                   = 46U,
    TRGSEL1_SRC_LU_OUT1B                   = 47U,
    TRGSEL1_SRC_LU_OUT2B                   = 48U,
    TRGSEL1_SRC_LU_OUT3B                   = 49U,
    TRGSEL1_SRC_PTIMER0_ADCCH0_TRIG        = 50U,
    TRGSEL1_SRC_PTIMER0_PULSE_OUT          = 51U,
    TRGSEL1_SRC_PTIMER1_ADCCH0_TRIG        = 52U,
    TRGSEL1_SRC_PTIMER1_PULSE_OUT          = 53U,
    TRGSEL1_SRC_RTC_ALARM                  = 54U,
    TRGSEL1_SRC_RTC_SECOND                 = 55U,
    TRGSEL1_SRC_ADC0_COCO0                 = 60U,
    TRGSEL1_SRC_ADC0_COCO1                 = 61U,
    TRGSEL1_SRC_ADC1_COCO0                 = 62U,
    TRGSEL1_SRC_ADC1_COCO1                 = 63U,
    TRGSEL1_SRC_GPIOA_TRG                  = 64U,
    TRGSEL1_SRC_GPIOB_TRG                  = 65U,
    TRGSEL1_SRC_GPIOC_TRG                  = 66U,
    TRGSEL1_SRC_GPIOD_TRG                  = 67U,
    TRGSEL1_SRC_GPIOE_TRG                  = 68U,
    TRGSEL1_SRC_FCUART0_RX_DONE            = 69U,
    TRGSEL1_SRC_FCUART0_TX_DONE            = 70U,
    TRGSEL1_SRC_FCUART0_RX_IDLE            = 71U,
    TRGSEL1_SRC_FCUART1_RX_DONE            = 72U,
    TRGSEL1_SRC_FCUART1_TX_DONE            = 73U,
    TRGSEL1_SRC_FCUART1_RX_IDLE            = 74U,
    TRGSEL1_SRC_FCUART2_RX_DONE            = 75U,
    TRGSEL1_SRC_FCUART2_TX_DONE            = 76U,
    TRGSEL1_SRC_FCUART2_RX_IDLE            = 77U,
    TRGSEL1_SRC_FCIIC0_MASTER_TRG          = 78U,
    TRGSEL1_SRC_FCIIC0_SLAVE_TRG           = 79U,
    TRGSEL1_SRC_FCIIC1_MASTER_TRG          = 80U,
    TRGSEL1_SRC_FCIIC1_SLAVE_TRG           = 81U,
    TRGSEL1_SRC_FCSPI0_FRAME               = 82U,
    TRGSEL1_SRC_FCSPI0_RX_DONE             = 83U,
    TRGSEL1_SRC_FCSPI1_FRAME               = 84U,
    TRGSEL1_SRC_FCSPI1_RX_DONE             = 85U,
    TRGSEL1_SRC_FCSPI2_FRAME               = 86U,
    TRGSEL1_SRC_FCSPI2_RX_DONE             = 87U,
    TRGSEL1_SRC_TRGSEL1_INPUT0             = 88U,
    TRGSEL1_SRC_TRGSEL1_INPUT1             = 89U,
    TRGSEL1_SRC_TRGSEL1_INPUT2             = 90U,
    TRGSEL1_SRC_TRGSEL1_INPUT3             = 91U,
//    TRGSEL1_SRC_ENET_PPS0                  = 92U,
//    TRGSEL1_SRC_ENET_PPS1                  = 93U,
//    TRGSEL1_SRC_ENET_PPS2                  = 94U,
//    TRGSEL1_SRC_ENET_PPS3                  = 95U,
    TRGSEL1_SRC_FCUART3_RX_DONE            = 100U,
    TRGSEL1_SRC_FCUART3_TX_DONE            = 101U,
    TRGSEL1_SRC_FCUART3_RX_IDLE            = 102U,
    TRGSEL1_SRC_FCUART4_RX_DONE            = 103U,
    TRGSEL1_SRC_FCUART4_TX_DONE            = 104U,
    TRGSEL1_SRC_FCUART4_RX_IDLE            = 105U,
    TRGSEL1_SRC_FCUART5_RX_DONE            = 106U,
    TRGSEL1_SRC_FCUART5_TX_DONE            = 107U,
    TRGSEL1_SRC_FCUART5_RX_IDLE            = 108U,
    TRGSEL1_SRC_FCSPI3_FRAME               = 109U,
    TRGSEL1_SRC_FCSPI3_RX_DONE             = 110U,
    TRGSEL1_SRC_FTU6_RELOAD_TRG            = 111U,
    TRGSEL1_SRC_FTU6_MATCH_TRG             = 112U,
    TRGSEL1_SRC_FTU7_RELOAD_TRG            = 113U,
    TRGSEL1_SRC_FTU7_MATCH_TRG             = 114U
} TrgSel1_SourceType;

/**
 * @brief TrgSel instance 2 trigger sources
 *
 */
typedef enum
{
    TRGSEL2_SRC_VSS                        = 0U,
    TRGSEL2_SRC_VDD                        = 1U,
    TRGSEL2_SRC_TRGSEL_OUT0                = 2U,
    TRGSEL2_SRC_TRGSEL_OUT1                = 3U,
    TRGSEL2_SRC_TRGSEL_OUT2                = 4U,
    TRGSEL2_SRC_TRGSEL_OUT3                = 5U,
    TRGSEL2_SRC_TRGSEL_OUT4                = 6U,
    TRGSEL2_SRC_TRGSEL_OUT5                = 7U,
    TRGSEL2_SRC_TRGSEL_OUT6                = 8U,
    TRGSEL2_SRC_TRGSEL_OUT7                = 9U,
    TRGSEL2_SRC_FTU_FLT0                   = 10U,
    TRGSEL2_SRC_FTU_FLT1                   = 11U,
    TRGSEL2_SRC_FTU_FLT2                   = 12U,
    TRGSEL2_SRC_FTU_FLT3                   = 13U,
    TRGSEL2_SRC_FTU_FLT4                   = 14U,
    TRGSEL2_SRC_FTU_FLT5                   = 15U,
    TRGSEL2_SRC_FTU_FLT6                   = 16U,
    TRGSEL2_SRC_FTU_FLT7                   = 17U,
    TRGSEL2_SRC_FTU_FLT8                   = 18U,
    TRGSEL2_SRC_FTU_FLT9                   = 19U,
    TRGSEL2_SRC_FTU_FLT10                  = 20U,
    TRGSEL2_SRC_FTU_FLT11                  = 21U,
    TRGSEL2_SRC_FTU_FLT12                  = 22U,
    TRGSEL2_SRC_FTU_FLT13                  = 23U,
    TRGSEL2_SRC_FTU_FLT14                  = 24U,
    TRGSEL2_SRC_FTU_FLT15                  = 25U,
    TRGSEL2_SRC_FTU_FLT16                  = 26U,
    TRGSEL2_SRC_FTU_FLT17                  = 27U,
    TRGSEL2_SRC_FTU_FLT18                  = 28U,
    TRGSEL2_SRC_FTU_FLT19                  = 29U,
    TRGSEL2_SRC_FTU_FLT20                  = 30U,
    TRGSEL2_SRC_FTU_FLT21                  = 31U
} TrgSel2_SourceType;

/**
 * @brief TrgSel instance 3 trigger sources
 *
 */
typedef enum
{
    TRGSEL3_SRC_VSS                        = 0U,
    TRGSEL3_SRC_VDD                        = 1U,
    TRGSEL3_SRC_TRGSEL_OUT0                = 2U,
    TRGSEL3_SRC_TRGSEL_OUT1                = 3U,
    TRGSEL3_SRC_TRGSEL_OUT2                = 4U,
    TRGSEL3_SRC_TRGSEL_OUT3                = 5U,
    TRGSEL3_SRC_TRGSEL_OUT4                = 6U,
    TRGSEL3_SRC_TRGSEL_OUT5                = 7U,
    TRGSEL3_SRC_TRGSEL_OUT6                = 8U,
    TRGSEL3_SRC_TRGSEL_OUT7                = 9U,
    TRGSEL3_SRC_PTA2_IN                    = 10U,
    TRGSEL3_SRC_PTA3_IN                    = 11U,
    TRGSEL3_SRC_PTA9_IN                    = 12U,
    TRGSEL3_SRC_PTA10_IN                   = 13U,
    TRGSEL3_SRC_PTA11_IN                   = 14U,
    TRGSEL3_SRC_PTA12_IN                   = 15U,
    TRGSEL3_SRC_PTA14_IN                   = 16U,
    TRGSEL3_SRC_PTA30_IN                   = 17U,
    TRGSEL3_SRC_PTB4_IN                    = 18U,
    TRGSEL3_SRC_PTB5_IN                    = 19U,
    TRGSEL3_SRC_PTB12_IN                   = 20U,
    TRGSEL3_SRC_PTB13_IN                   = 21U,
    TRGSEL3_SRC_PTB14_IN                   = 22U,
    TRGSEL3_SRC_PTB15_IN                   = 23U,
    TRGSEL3_SRC_PTB16_IN                   = 24U,
    TRGSEL3_SRC_PTB17_IN                   = 25U,
    TRGSEL3_SRC_PTC0_IN                    = 26U,
    TRGSEL3_SRC_PTC1_IN                    = 27U,
    TRGSEL3_SRC_PTC2_IN                    = 28U,
    TRGSEL3_SRC_PTC3_IN                    = 29U,
    TRGSEL3_SRC_PTC6_IN                    = 30U,
    TRGSEL3_SRC_PTC7_IN                    = 31U,
    TRGSEL3_SRC_PTD15_IN                   = 32U,
    TRGSEL3_SRC_PTD16_IN                   = 33U,
    TRGSEL3_SRC_PTE4_IN                    = 34U,
    TRGSEL3_SRC_PTE5_IN                    = 35U,
    TRGSEL3_SRC_PTE19_IN                   = 36U,
    TRGSEL3_SRC_PTA2_OUT                   = 37U,
    TRGSEL3_SRC_PTA3_OUT                   = 38U,
    TRGSEL3_SRC_PTA9_OUT                   = 39U,
    TRGSEL3_SRC_PTA10_OUT                  = 40U,
    TRGSEL3_SRC_PTA11_OUT                  = 41U,
    TRGSEL3_SRC_PTA12_OUT                  = 42U,
    TRGSEL3_SRC_PTA14_OUT                  = 43U,
    TRGSEL3_SRC_PTA30_OUT                  = 44U,
    TRGSEL3_SRC_PTB4_OUT                   = 45U,
    TRGSEL3_SRC_PTB5_OUT                   = 46U,
    TRGSEL3_SRC_PTB12_OUT                  = 47U,
    TRGSEL3_SRC_PTB13_OUT                  = 48U,
    TRGSEL3_SRC_PTB14_OUT                  = 49U,
    TRGSEL3_SRC_PTB15_OUT                  = 50U,
    TRGSEL3_SRC_PTB16_OUT                  = 51U,
    TRGSEL3_SRC_PTB17_OUT                  = 52U,
    TRGSEL3_SRC_PTC0_OUT                   = 53U,
    TRGSEL3_SRC_PTC1_OUT                   = 54U,
    TRGSEL3_SRC_PTC2_OUT                   = 55U,
    TRGSEL3_SRC_PTC3_OUT                   = 56U,
    TRGSEL3_SRC_PTC6_OUT                   = 57U,
    TRGSEL3_SRC_PTC7_OUT                   = 58U,
    TRGSEL3_SRC_PTD15_OUT                  = 59U,
    TRGSEL3_SRC_PTD16_OUT                  = 60U,
    TRGSEL3_SRC_PTE4_OUT                   = 61U,
    TRGSEL3_SRC_PTE5_OUT                   = 62U,
    TRGSEL3_SRC_PTE19_OUT                  = 63U
} TrgSel3_SourceType;

#endif
